### ISSUE TITLE
Physical copy?

### ISSUE THREAD

**Issue by berquist** [jrblevin/markdown-mode-guide#2]
Even though it would be frozen in time, I'd really like a physical copy. Maybe a [print-on-demand](https://www.bookbaby.com/print-on-demand) service would make this possible for a small number of copies?

**Comment by jrblevin** [comment]
I thought about doing print-on-demand, but I wasn’t sure if there was demand, so thanks for letting me know you’re interested. I’ll update this issue when it’s ready.

**Comment by jrblevin** [comment]
Good progress to report on the paperback version. I got a hardcopy proof today and it looks great. I’m told it should be [available for sale on Amazon](http://www.amazon.com/exec/obidos/ASIN/197811883X/jblevins-20) in 3-5 days.

**Comment by jrblevin** [comment]
It's available already. That was much faster than expected.
